-- Create Default Company
INSERT INTO company (date_modified, date_created, active_status, name, name_short, co_entity_type, ecash_process_type)
VALUES (NOW(), NOW(), 'inactive', 'Default Company', 'dfalt','pseudo',2);

SELECT @default_company_id := company_id FROM company WHERE name_short = 'dfalt';

-- Create Default Loan Type for Default Company
INSERT INTO loan_type (date_modified, date_created, active_status,company_id,name,name_short,abbreviation)
VALUES (NOW(), NOW(), 'active',  @default_company_id, 'Default PayDay Loan','default_pd_loan','DF');

SELECT @default_loan_type := loan_type_id FROM loan_type WHERE name_short = 'default_pd_loan' AND company_id = @default_company_id;

-- Create Default eCash Ruleset
INSERT INTO rule_set (date_modified, date_created, active_status, name, loan_type_id, date_effective)
VALUES (NOW(), NOW(), 'active', 'Default Pay Day Loan Ruleset', @default_loan_type, NOW());

SELECT @ecash_ruleset := rule_set_id FROM rule_set WHERE name = 'Default Pay Day Loan Ruleset' AND loan_type_id = @default_loan_type;

-- Create Default CFE Ruleset
INSERT INTO cfe_rule_set (date_modified, date_created, active_status, name, loan_type_id, date_effective)
VALUES (NOW(), NOW(), 'active', 'Default Pay Day Loan Ruleset', @default_loan_type, NOW());

SELECT @cfe_ruleset := cfe_rule_set_id FROM cfe_rule_set WHERE name = 'Default Pay Day Loan Ruleset' AND loan_type_id = @default_loan_type;

-- Populate CFE rules

INSERT INTO cfe_rule 
(date_modified, date_created, cfe_rule_id, cfe_rule_set_id, name, cfe_event_id, salience)
VALUES
(NOW(),NOW(),null,@cfe_ruleset,'Accepted_approved',5,36),
(NOW(),NOW(),null,@cfe_ruleset,'Accepted_approved_followup',5,38),
(NOW(),NOW(),null,@cfe_ruleset,'Status_change_agree',3,34),
(NOW(),NOW(),null,@cfe_ruleset,'Status_Change_made_arrangments',3,29),
(NOW(),NOW(),null,@cfe_ruleset,'Accepted_approved_followup_react',5,39),
(NOW(),NOW(),null,@cfe_ruleset,'Accepted_approved_react',5,37),
(NOW(),NOW(),null,@cfe_ruleset,'Status_change_bankruptcy_queued',3,22),
(NOW(),NOW(),null,@cfe_ruleset,'add_follow_up_verification_react',4,28),
(NOW(),NOW(),null,@cfe_ruleset,'Status_change_ready_quickchecks',3,17),
(NOW(),NOW(),null,@cfe_ruleset,'Status_change_withdrawn',3,24),
(NOW(),NOW(),null,@cfe_ruleset,'Status_change_pre_fund',3,26),
(NOW(),NOW(),null,@cfe_ruleset,'Status_change_bankruptcy_dequeued',3,18),
(NOW(),NOW(),null,@cfe_ruleset,'Status_change_denied',3,25),
(NOW(),NOW(),null,@cfe_ruleset,'add_follow_up_active',4,31),
(NOW(),NOW(),null,@cfe_ruleset,'add_follow_up_verification',4,27),
(NOW(),NOW(),null,@cfe_ruleset,'Status_change_sent_external',3,19),
(NOW(),NOW(),null,@cfe_ruleset,'Status_change_verified_bankruptcy',3,23),
(NOW(),NOW(),null,@cfe_ruleset,'Status_change_active',3,21),
(NOW(),NOW(),null,@cfe_ruleset,'Status_change_unverified_bankruptcy',3,20),
(NOW(),NOW(),null,@cfe_ruleset,'Status_change_sent_quickchecks',3,16),
(NOW(),NOW(),null,@cfe_ruleset,'Status_Change_underwriting_react',3,15),
(NOW(),NOW(),null,@cfe_ruleset,'Status_Change_underwriting_nonreact',3,14),
(NOW(),NOW(),null,@cfe_ruleset,'Status_Change_fraud',3,9),
(NOW(),NOW(),null,@cfe_ruleset,'Status_Change_collections_contact',3,11),
(NOW(),NOW(),null,@cfe_ruleset,'Status_Change_collections_new',3,13),
(NOW(),NOW(),null,@cfe_ruleset,'Status_Change_verification_react',3,8),
(NOW(),NOW(),null,@cfe_ruleset,'Status_Change_verification_nonreact',3,7),
(NOW(),NOW(),null,@cfe_ruleset,'add_follow_up_underwriting',4,3),
(NOW(),NOW(),null,@cfe_ruleset,'Status_Change_PastDue',3,12),
(NOW(),NOW(),null,@cfe_ruleset,'Status_change_funding_failed',3,5),
(NOW(),NOW(),null,@cfe_ruleset,'DO NOT DELETE THIS RULE, OR ELSE!',1,32),
(NOW(),NOW(),null,@cfe_ruleset,'Default Queue Insert react',5,35),
(NOW(),NOW(),null,@cfe_ruleset,'add_follow_up_collections2',4,1),
(NOW(),NOW(),null,@cfe_ruleset,'Status_Change_high_risk',3,6),
(NOW(),NOW(),null,@cfe_ruleset,'add_follow_up_underwriting_react',4,2),
(NOW(),NOW(),null,@cfe_ruleset,'add_follow_up_funding_failed',4,41),
(NOW(),NOW(),null,@cfe_ruleset,'add_follow_up_collections1',4,4),
(NOW(),NOW(),null,@cfe_ruleset,'add_follow_up_past_due',4,40),
(NOW(),NOW(),null,@cfe_ruleset,'Status_Change_inactive',3,0),
(NOW(),NOW(),null,@cfe_ruleset,'Default Queue Insert',5,33),
(NOW(),NOW(),null,@cfe_ruleset,'add_follow_up_amortization',4,44),
(NOW(),NOW(),null,@cfe_ruleset,'add_follow_up_pre_fund',4,43),
(NOW(),NOW(),null,@cfe_ruleset,'add_follow_up_servicing_hold',4,42);


INSERT INTO cfe_rule_action (date_modified, date_created, cfe_rule_action_id, cfe_rule_id, cfe_action_id,params, sequence_no, rule_action_type)
VALUES
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Accepted_approved" AND cfe_rule_set_id = @cfe_ruleset),6,'a:1:{s:5:"queue";s:12:"underwriting";}',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Accepted_approved_followup" AND cfe_rule_set_id = @cfe_ruleset),6,'a:1:{s:5:"queue";s:12:"underwriting";}',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_Change_made_arrangments" AND cfe_rule_set_id = @cfe_ruleset),7,'b:0;',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_change_agree" AND cfe_rule_set_id = @cfe_ruleset),6,'a:1:{s:5:"queue";s:16:"customer_service";}',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Accepted_approved_followup_react" AND cfe_rule_set_id = @cfe_ruleset),6,'a:1:{s:5:"queue";s:18:"underwriting_react";}',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "add_follow_up_verification_react" AND cfe_rule_set_id = @cfe_ruleset),6,'a:1:{s:5:"queue";s:18:"verification_react";}',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_change_bankruptcy_queued" AND cfe_rule_set_id = @cfe_ruleset),7,'b:0;',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Accepted_approved_react" AND cfe_rule_set_id = @cfe_ruleset),6,'a:1:{s:5:"queue";s:18:"underwriting_react";}',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "add_follow_up_servicing_hold" AND cfe_rule_set_id = @cfe_ruleset),6,'a:1:{s:5:"queue";s:16:"customer_service";}',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "add_follow_up_pre_fund" AND cfe_rule_set_id = @cfe_ruleset),6,'a:1:{s:5:"queue";s:16:"customer_service";}',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "add_follow_up_amortization" AND cfe_rule_set_id = @cfe_ruleset),6,'a:1:{s:5:"queue";s:12:"action_queue";}',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Default Queue Insert" AND cfe_rule_set_id = @cfe_ruleset),6,'a:1:{s:5:"queue";s:12:"verification";}',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_Change_inactive" AND cfe_rule_set_id = @cfe_ruleset),7,'b:0;',1,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "add_follow_up_past_due" AND cfe_rule_set_id = @cfe_ruleset),6,'a:1:{s:5:"queue";s:16:"customer_service";}',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "add_follow_up_collections1" AND cfe_rule_set_id = @cfe_ruleset),6,'a:1:{s:5:"queue";s:19:"collections_general";}',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "add_follow_up_funding_failed" AND cfe_rule_set_id = @cfe_ruleset),6,'a:1:{s:5:"queue";s:16:"customer_service";}',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "add_follow_up_underwriting_react" AND cfe_rule_set_id = @cfe_ruleset),6,'a:1:{s:5:"queue";s:18:"underwriting_react";}',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_Change_high_risk" AND cfe_rule_set_id = @cfe_ruleset),6,'a:1:{s:5:"queue";s:15:"high_risk_queue";}',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "add_follow_up_collections2" AND cfe_rule_set_id = @cfe_ruleset),6,'a:1:{s:5:"queue";s:19:"collections_general";}',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Default Queue Insert react" AND cfe_rule_set_id = @cfe_ruleset),6,'a:1:{s:5:"queue";s:18:"verification_react";}',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "DO NOT DELETE THIS RULE, OR ELSE!" AND cfe_rule_set_id = @cfe_ruleset),3,'b:0;',111,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_change_funding_failed" AND cfe_rule_set_id = @cfe_ruleset),7,'b:0;',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_Change_PastDue" AND cfe_rule_set_id = @cfe_ruleset),6,'a:1:{s:5:"queue";s:15:"collections_new";}',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "add_follow_up_underwriting" AND cfe_rule_set_id = @cfe_ruleset),6,'a:1:{s:5:"queue";s:12:"underwriting";}',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_Change_verification_nonreact" AND cfe_rule_set_id = @cfe_ruleset),6,'a:1:{s:5:"queue";s:12:"verification";}',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_Change_verification_react" AND cfe_rule_set_id = @cfe_ruleset),6,'a:1:{s:5:"queue";s:18:"verification_react";}',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_Change_collections_new" AND cfe_rule_set_id = @cfe_ruleset),6,'a:1:{s:5:"queue";s:15:"collections_new";}',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_Change_collections_contact" AND cfe_rule_set_id = @cfe_ruleset),6,'a:1:{s:5:"queue";s:19:"collections_general";}',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_Change_fraud" AND cfe_rule_set_id = @cfe_ruleset),6,'a:1:{s:5:"queue";s:11:"fraud_queue";}',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_Change_underwriting_nonreact" AND cfe_rule_set_id = @cfe_ruleset),6,'a:1:{s:5:"queue";s:12:"underwriting";}',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_Change_underwriting_react" AND cfe_rule_set_id = @cfe_ruleset),6,'a:1:{s:5:"queue";s:18:"underwriting_react";}',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_change_sent_quickchecks" AND cfe_rule_set_id = @cfe_ruleset),7,'b:0;',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_change_active" AND cfe_rule_set_id = @cfe_ruleset),7,'b:0;',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_change_unverified_bankruptcy" AND cfe_rule_set_id = @cfe_ruleset),7,'b:0;',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_change_sent_external" AND cfe_rule_set_id = @cfe_ruleset),7,'b:0;',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_change_verified_bankruptcy" AND cfe_rule_set_id = @cfe_ruleset),7,'b:0;',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "add_follow_up_verification" AND cfe_rule_set_id = @cfe_ruleset),6,'a:1:{s:5:"queue";s:12:"verification";}',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "add_follow_up_active" AND cfe_rule_set_id = @cfe_ruleset),6,'a:1:{s:5:"queue";s:16:"customer_service";}',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_change_denied" AND cfe_rule_set_id = @cfe_ruleset),7,'b:0;',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_change_bankruptcy_dequeued" AND cfe_rule_set_id = @cfe_ruleset),7,'b:0;',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_change_pre_fund" AND cfe_rule_set_id = @cfe_ruleset),7,'b:0;',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_change_withdrawn" AND cfe_rule_set_id = @cfe_ruleset),7,'b:0;',0,0),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_change_ready_quickchecks" AND cfe_rule_set_id = @cfe_ruleset),7,'b:0;',0,0);

INSERT INTO cfe_rule_condition (date_modified, date_created, cfe_rule_condition_id, cfe_rule_id, operator, operand1, operand1_type, operand2, operand2_type, sequence_no)
VALUES
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Accepted_approved" AND cfe_rule_set_id = @cfe_ruleset),'equals','is_react','0','no','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Accepted_approved" AND cfe_rule_set_id = @cfe_ruleset),'equals','application_status','0','queued::underwriting::applicant::*root','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Accepted_approved_followup" AND cfe_rule_set_id = @cfe_ruleset),'equals','application_status','0','follow_up::underwriting::applicant::*root','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Accepted_approved_followup" AND cfe_rule_set_id = @cfe_ruleset),'equals','is_react','0','no','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_Change_made_arrangments" AND cfe_rule_set_id = @cfe_ruleset),'equals','application_status','0','current::arrangements::collections::customer::*root','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_change_agree" AND cfe_rule_set_id = @cfe_ruleset),'equals','application_status','0','agree::prospect::*root','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Accepted_approved_followup_react" AND cfe_rule_set_id = @cfe_ruleset),'equals','is_react','0','yes','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Accepted_approved_followup_react" AND cfe_rule_set_id = @cfe_ruleset),'equals','application_status','0','follow_up::underwriting::applicant::*root','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Accepted_approved_react" AND cfe_rule_set_id = @cfe_ruleset),'equals','is_react','0','yes','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Accepted_approved_react" AND cfe_rule_set_id = @cfe_ruleset),'equals','application_status','0','queued::underwriting::applicant::*root','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_change_funding_failed" AND cfe_rule_set_id = @cfe_ruleset),'equals','application_status','0','funding_failed::servicing::customer::*root','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_Change_PastDue" AND cfe_rule_set_id = @cfe_ruleset),'equals','application_status','0','past_due::servicing::customer::*root','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "add_follow_up_underwriting" AND cfe_rule_set_id = @cfe_ruleset),'equals','status_level_1','0','underwriting','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "add_follow_up_underwriting" AND cfe_rule_set_id = @cfe_ruleset),'equals','is_react','0','no','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "add_follow_up_underwriting" AND cfe_rule_set_id = @cfe_ruleset),'equals','status_level_2','0','applicant','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_Change_verification_nonreact" AND cfe_rule_set_id = @cfe_ruleset),'equals','is_react','0','no','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_Change_verification_nonreact" AND cfe_rule_set_id = @cfe_ruleset),'equals','application_status','0','queued::verification::applicant::*root','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_Change_verification_react" AND cfe_rule_set_id = @cfe_ruleset),'equals','is_react','0','yes','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_Change_verification_react" AND cfe_rule_set_id = @cfe_ruleset),'equals','application_status','0','queued::verification::applicant::*root','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_Change_collections_new" AND cfe_rule_set_id = @cfe_ruleset),'equals','application_status','0','new::collections::customer::*root','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_Change_collections_contact" AND cfe_rule_set_id = @cfe_ruleset),'equals','application_status','0','queued::contact::collections::customer::*root','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_Change_fraud" AND cfe_rule_set_id = @cfe_ruleset),'equals','application_status','0','queued::fraud::applicant::*root','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_Change_underwriting_nonreact" AND cfe_rule_set_id = @cfe_ruleset),'equals','application_status','0','queued::underwriting::applicant::*root','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_Change_underwriting_nonreact" AND cfe_rule_set_id = @cfe_ruleset),'equals','is_react','0','no','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_Change_underwriting_react" AND cfe_rule_set_id = @cfe_ruleset),'equals','application_status','0','queued::underwriting::applicant::*root','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_Change_underwriting_react" AND cfe_rule_set_id = @cfe_ruleset),'equals','is_react','0','yes','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_change_sent_quickchecks" AND cfe_rule_set_id = @cfe_ruleset),'equals','application_status','0','sent::quickcheck::collections::customer::*root','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_change_active" AND cfe_rule_set_id = @cfe_ruleset),'equals','application_status','0','active::servicing::customer::*root','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_change_sent_external" AND cfe_rule_set_id = @cfe_ruleset),'equals','application_status','0','sent::external_collections::*root','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_change_verified_bankruptcy" AND cfe_rule_set_id = @cfe_ruleset),'equals','application_status','0','verified::bankruptcy::collections::customer::*root','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "add_follow_up_verification" AND cfe_rule_set_id = @cfe_ruleset),'equals','status_level_2','0','applicant','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "add_follow_up_verification" AND cfe_rule_set_id = @cfe_ruleset),'equals','is_react','0','no','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "add_follow_up_verification" AND cfe_rule_set_id = @cfe_ruleset),'equals','status_level_1','0','verification','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "add_follow_up_active" AND cfe_rule_set_id = @cfe_ruleset),'equals','application_status','0','active::servicing::customer::*root','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_change_denied" AND cfe_rule_set_id = @cfe_ruleset),'equals','application_status','0','denied::applicant::*root','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_change_bankruptcy_dequeued" AND cfe_rule_set_id = @cfe_ruleset),'equals','application_status','0','dequeued::bankruptcy::collections::customer::*root','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_change_pre_fund" AND cfe_rule_set_id = @cfe_ruleset),'equals','application_status','0','approved::servicing::customer::*root','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_change_withdrawn" AND cfe_rule_set_id = @cfe_ruleset),'equals','application_status','0','withdrawn::applicant::*root','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_change_ready_quickchecks" AND cfe_rule_set_id = @cfe_ruleset),'equals','application_status','0','sent::quickcheck::collections::customer::*root','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "add_follow_up_verification_react" AND cfe_rule_set_id = @cfe_ruleset),'equals','status_level_2','0','applicant','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "add_follow_up_verification_react" AND cfe_rule_set_id = @cfe_ruleset),'equals','status_level_1','0','verification','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "add_follow_up_verification_react" AND cfe_rule_set_id = @cfe_ruleset),'equals','is_react','0','yes','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_change_bankruptcy_queued" AND cfe_rule_set_id = @cfe_ruleset),'equals','application_status','0','unverified::bankruptcy::collections::customer::*root','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "add_follow_up_collections2" AND cfe_rule_set_id = @cfe_ruleset),'equals','status_level_2','0','collections','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Default Queue Insert react" AND cfe_rule_set_id = @cfe_ruleset),'equals','is_react','0','yes','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Default Queue Insert react" AND cfe_rule_set_id = @cfe_ruleset),'equals','application_status','0','queued::verification::applicant::*root','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "add_follow_up_underwriting_react" AND cfe_rule_set_id = @cfe_ruleset),'equals','status_level_1','0','underwriting','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_Change_high_risk" AND cfe_rule_set_id = @cfe_ruleset),'equals','application_status','0','queued::high_risk::applicant::*root','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "add_follow_up_underwriting_react" AND cfe_rule_set_id = @cfe_ruleset),'equals','is_react','0','yes','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "add_follow_up_funding_failed" AND cfe_rule_set_id = @cfe_ruleset),'equals','application_status','0','funding_failed::servicing::customer::*root','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "add_follow_up_underwriting_react" AND cfe_rule_set_id = @cfe_ruleset),'equals','status_level_2','0','applicant','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Default Queue Insert" AND cfe_rule_set_id = @cfe_ruleset),'equals','application_status','0','queued::verification::applicant::*root','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Status_Change_inactive" AND cfe_rule_set_id = @cfe_ruleset),'equals','application_status','0','paid::customer::*root','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "add_follow_up_past_due" AND cfe_rule_set_id = @cfe_ruleset),'equals','application_status','0','past_due::servicing::customer::*root','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "add_follow_up_collections1" AND cfe_rule_set_id = @cfe_ruleset),'equals','status_level_1','0','collections','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "add_follow_up_amortization" AND cfe_rule_set_id = @cfe_ruleset),'equals','application_status','0','amortization::bankruptcy::collections::customer::*root','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "Default Queue Insert" AND cfe_rule_set_id = @cfe_ruleset),'equals','is_react','0','no','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "add_follow_up_servicing_hold" AND cfe_rule_set_id = @cfe_ruleset),'equals','application_status','0','hold::servicing::customer::*root','1',1),
(NOW(),NOW(),null,(SELECT cfe_rule_id FROM cfe_rule WHERE name = "add_follow_up_pre_fund" AND cfe_rule_set_id = @cfe_ruleset),'equals','application_status','0','approved::servicing::customer::*root','1',1);

-- Set Default eCash ruleset components

INSERT INTO rule_set_component (date_modified, date_created, active_status, rule_set_id, rule_component_id, sequence_no)
VALUES
(NOW(),NOW(),"active",@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "return_transaction_fee"),19),
(NOW(),NOW(),"active",@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "max_svc_charge_failures"),12),
(NOW(),NOW(),"active",@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "principal_payment"),17),
(NOW(),NOW(),"active",@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "service_charge"),20),
(NOW(),NOW(),"active",@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "react_amount_increase"),0),
(NOW(),NOW(),"active",@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "max_react_loan_amount"),0),
(NOW(),NOW(),"active",@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "max_num_arr_payments"),9),
(NOW(),NOW(),"active",@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "arrangements_met_discount"),1),
(NOW(),NOW(),"active",@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "max_num_arr_payment_failed"),10),
(NOW(),NOW(),"active",@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "debit_frequency"),5),
(NOW(),NOW(),"active",@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "new_loan_amount"),15),
(NOW(),NOW(),"active",@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "cancelation_delay"),4),
(NOW(),NOW(),"active",@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "watch_period"),21),
(NOW(),NOW(),"active",@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "grace_period"),7),
(NOW(),NOW(),"active",@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "loan_percentage"),22),
(NOW(),NOW(),"active",@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "loan_amount_increment"),23),
(NOW(),NOW(),"active",@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "loan_cap"),24),
(NOW(),NOW(),"active",@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "loan_type_model"),25),
(NOW(),NOW(),"active",@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "moneygram_fee"),30),
(NOW(),NOW(),"active",@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "settlement_offer"),0),
(NOW(),NOW(),"active",@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "IDV_CALL"),36),
(NOW(),NOW(),"active",@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "require_bank_account"),37),
(NOW(),NOW(),"active",@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "minimum_loan_amount"),0),
(NOW(),NOW(),"active",@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "one_time_arrangement_grace"),36),
(NOW(),NOW(),"active",@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "interest_rounding"),48),
(NOW(),NOW(),"active",@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "FUNDUPD_CALL"),36),
(NOW(),NOW(),"active",@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "one_time_arrangement_min"),36),
(NOW(),NOW(),"active",@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "notification_after_partial"),36),
(NOW(),NOW(),"active",@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "action_after_partial"),36);


-- Populate Default Parm values

INSERT INTO rule_set_component_parm_value (date_modified, date_created, agent_id, rule_set_id, rule_component_id, rule_component_parm_id, parm_value)
VALUES
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "return_transaction_fee"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "return_transaction_fee") AND parm_name = "return_transaction_fee"),"15"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "max_svc_charge_failures"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "max_svc_charge_failures") AND parm_name = "max_svc_charge_failures"),"2"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "principal_payment"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "principal_payment") AND parm_name = "principal_payment_amount"),"50"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "principal_payment"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "principal_payment") AND parm_name = "principal_payment_type"),"Percentage"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "principal_payment"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "principal_payment") AND parm_name = "principal_payment_percentage"),"10"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "principal_payment"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "principal_payment") AND parm_name = "min_renew_prin_pmt_prcnt"),"10"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "service_charge"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "service_charge") AND parm_name = "max_svc_charge_only_pmts"),"4"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "service_charge"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "service_charge") AND parm_name = "svc_charge_percentage"),"30"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "service_charge"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "service_charge") AND parm_name = "svc_charge_type"),"fixed"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "service_charge"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "service_charge") AND parm_name = "max_renew_svc_charge_only_pmts"),"10"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "service_charge"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "service_charge") AND parm_name = "interest_accrual_limit"),"999"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "react_amount_increase"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "react_amount_increase") AND parm_name = "react_loan_amnt_increase"),"50"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "max_react_loan_amount"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "max_react_loan_amount") AND parm_name = "800"),"500"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "max_react_loan_amount"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "max_react_loan_amount") AND parm_name = "1200"),"500"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "max_num_arr_payments"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "max_num_arr_payments") AND parm_name = "100"),"2"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "max_num_arr_payments"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "max_num_arr_payments") AND parm_name = "200"),"5"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "max_num_arr_payments"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "max_num_arr_payments") AND parm_name = "300"),"7"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "max_num_arr_payments"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "max_num_arr_payments") AND parm_name = "400"),"8"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "max_num_arr_payments"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "max_num_arr_payments") AND parm_name = "500"),"9"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "max_num_arr_payments"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "max_num_arr_payments") AND parm_name = "600"),"10"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "arrangements_met_discount"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "arrangements_met_discount") AND parm_name = "percentage_rate"),"10"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "max_num_arr_payment_failed"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "max_num_arr_payment_failed") AND parm_name = "100"),"2"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "max_num_arr_payment_failed"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "max_num_arr_payment_failed") AND parm_name = "200"),"5"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "max_num_arr_payment_failed"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "max_num_arr_payment_failed") AND parm_name = "300"),"7"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "max_num_arr_payment_failed"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "max_num_arr_payment_failed") AND parm_name = "400"),"8"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "max_num_arr_payment_failed"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "max_num_arr_payment_failed") AND parm_name = "500"),"9"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "max_num_arr_payment_failed"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "max_num_arr_payment_failed") AND parm_name = "600"),"10"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "debit_frequency"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "debit_frequency") AND parm_name = "weekly"),"every other pay period"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "debit_frequency"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "debit_frequency") AND parm_name = "bi_weekly"),"every pay period"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "debit_frequency"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "debit_frequency") AND parm_name = "twice_monthly"),"every pay period"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "debit_frequency"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "debit_frequency") AND parm_name = "monthly"),"every pay period"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "new_loan_amount"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "new_loan_amount") AND parm_name = "1000"),"150"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "new_loan_amount"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "new_loan_amount") AND parm_name = "1200"),"200"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "new_loan_amount"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "new_loan_amount") AND parm_name = "1700"),"200"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "new_loan_amount"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "new_loan_amount") AND parm_name = "2000"),"300"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "new_loan_amount"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "new_loan_amount") AND parm_name = "5000"),"300"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "cancelation_delay"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "cancelation_delay") AND parm_name = "cancelation_delay"),"3"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "watch_period"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "watch_period") AND parm_name = "watch_period"),"30"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "grace_period"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "grace_period") AND parm_name = "grace_period"),"10"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "loan_percentage"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "loan_percentage") AND parm_name = "0"),"20"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "loan_percentage"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "loan_percentage") AND parm_name = "1"),"20"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "loan_percentage"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "loan_percentage") AND parm_name = "2"),"25"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "loan_percentage"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "loan_percentage") AND parm_name = "3"),"25"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "loan_percentage"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "loan_percentage") AND parm_name = "4"),"25"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "loan_percentage"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "loan_percentage") AND parm_name = "5"),"25"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "loan_percentage"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "loan_percentage") AND parm_name = "6"),"25"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "loan_percentage"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "loan_percentage") AND parm_name = "7"),"25"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "loan_percentage"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "loan_percentage") AND parm_name = "8"),"25"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "loan_percentage"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "loan_percentage") AND parm_name = "9"),"25"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "loan_percentage"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "loan_percentage") AND parm_name = "10"),"25"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "loan_percentage"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "loan_percentage") AND parm_name = "11"),"25"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "loan_amount_increment"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "loan_amount_increment") AND parm_name = "loan_amount_increment"),"50"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "loan_cap"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "loan_cap") AND parm_name = "0"),"300"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "loan_cap"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "loan_cap") AND parm_name = "1"),"450"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "loan_cap"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "loan_cap") AND parm_name = "2"),"550"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "loan_cap"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "loan_cap") AND parm_name = "3"),"600"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "loan_cap"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "loan_cap") AND parm_name = "4"),"650"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "loan_cap"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "loan_cap") AND parm_name = "5"),"700"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "loan_cap"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "loan_cap") AND parm_name = "6"),"750"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "loan_cap"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "loan_cap") AND parm_name = "7"),"800"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "loan_cap"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "loan_cap") AND parm_name = "8"),"850"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "loan_cap"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "loan_cap") AND parm_name = "9"),"900"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "loan_cap"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "loan_cap") AND parm_name = "10"),"950"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "loan_cap"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "loan_cap") AND parm_name = "11"),"1000"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "loan_type_model"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "loan_type_model") AND parm_name = "loan_type_model"),"Payday"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "moneygram_fee"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "moneygram_fee") AND parm_name = "moneygram_fee"),"0"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "settlement_offer"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "settlement_offer") AND parm_name = "settlement_offer"),"60"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "IDV_CALL"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "IDV_CALL") AND parm_name = "IDV_CALL"),"default-perf"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "require_bank_account"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "require_bank_account") AND parm_name = "require_bank_account_enable"),"On"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "minimum_loan_amount"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "minimum_loan_amount") AND parm_name = "min_non_react"),"100"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "minimum_loan_amount"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "minimum_loan_amount") AND parm_name = "min_react"),"150"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "one_time_arrangement_grace"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "one_time_arrangement_grace") AND parm_name = "one_time_arrangement_grace"),"0"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "interest_rounding"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "interest_rounding") AND parm_name = "type"),"default"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "interest_rounding"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "interest_rounding") AND parm_name = "digit"),"2"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "FUNDUPD_CALL"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "FUNDUPD_CALL") AND parm_name = "FUNDUPD_CALL"),"default-fundupd"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "one_time_arrangement_min"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "one_time_arrangement_min") AND parm_name = "one_time_arrangement_min"),"25"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "notification_after_partial"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "notification_after_partial") AND parm_name = "notification_after_partial"),"2"),
(NOW(),NOW(),0,@ecash_ruleset,(SELECT rule_component_id FROM rule_component WHERE name_short = "action_after_partial"),(SELECT rule_component_parm_id FROM rule_component_parm WHERE rule_component_id = (SELECT rule_component_id FROM rule_component WHERE name_short = "action_after_partial") AND parm_name = "action_after_partial"),"Collections General");


