<?php

require_once realpath(dirname(__FILE__) . "/..") . "/config.php";

if (strtolower(EXECUTION_MODE) != 'live') 
{
	ini_set("soap.wsdl_cache_enabled", "0"); 
	ini_set("soap.wsdl_cache", "0"); 
}


require_once LIB_DIR . "/common_functions.php";
require_once LIB_DIR . "/RPC/RPC.class.php";

//eCash_RPC::Log()->write("New Connection");

/**
 * class must be loaded before auth started so that restoring soap-persistent class works properly
 */
$class = $_REQUEST['rpc_class'];

eCash_RPC::loadClass($class);

/**
 * if the wsdl request is INTERNAL (i.e. generated by the soap server itself), skip authentication
 */
if (!$_REQUEST['sct'] || !in_array($_REQUEST['sct'], eCash_RPC::genSelfWsdlToken()))
{
	/**
	 * the connecting RPC user MUST authenticate and have rights to use the class.
	 * any additional ACL rights must be implemented internally by the class
	 */
//	eCash_RPC::Log()->write("_SERVER \n---\n" . var_export($_SERVER,true) . "\n---\n");
	
	eCash_RPC_Auth::HTTP($_SERVER['PHP_AUTH_USER'], $_SERVER['PHP_AUTH_PW']);
	eCash_RPC_Auth::allowed($class, $_REQUEST['company']);

}

/**
 * if the uri is appended by 'wsdl', load the class in question, and output wsdl
 * only useful for SOAP.
 */
if(isset($_SERVER['QUERY_STRING']) &&  ( preg_match("/(&|\?)wsdl$/",$_SERVER['QUERY_STRING']))) 
{
	$rpc_mode = "wsdl";
}

/**
 * engage the RPC
 */
$rpc = eCash_RPC::Factory(($rpc_mode) ? $rpc_mode : "soap", $class, TRUE, TRUE);

//eCash_RPC::Log()->write("End Connection");

