CREATE TABLE IF NOT EXISTS `application` (
  `date_modified` timestamp NOT NULL default CURRENT_TIMESTAMP COMMENT "Convenience",
  `date_created` timestamp NOT NULL default '0000-00-00 00:00:00' COMMENT "Convenience",
  `company_id` int(10) unsigned NOT NULL default '0' COMMENT "What company this application belongs to",
  `application_id` int(10) unsigned NOT NULL default '0' COMMENT "Primary key",
  `archive_db2_id` int(10) unsigned default NULL COMMENT "Deprecated",
  `archive_mysql_id` int(10) unsigned default NULL COMMENT "Deprecated",
  `archive_cashline_id` int(10) unsigned default NULL COMMENT "Deprecated",
  `login_id` int(10) unsigned default NULL COMMENT "The applicant's login via another site",
  `is_react` enum('no','yes') NOT NULL COMMENT "Is this NOT the first application by this person?",
  `loan_type_id` int(10) unsigned NOT NULL default '0' COMMENT "Foreign key",
  `rule_set_id` int(10) unsigned default NULL COMMENT "Foreign key" COMMENT "Foreign key",
  `enterprise_site_id` int(10) unsigned NOT NULL default '0' COMMENT "Foreign key",
  `application_status_id` int(10) unsigned NOT NULL default '0' COMMENT "Foreign key",
  `date_application_status_set` timestamp NOT NULL default '0000-00-00 00:00:00' COMMENT "See also: `status_history`",
  `date_next_contact` timestamp NULL default NULL COMMENT "If the person stated a better time to call back",
  `ip_address` varchar(40) NOT NULL default '' COMMENT "Fraud detection likes this, but do not trust it to be accurate",
  `application_type` enum('paperless','paper') NOT NULL default 'paperless' COMMENT "Submitted via one of OLP's sites?",
  `bank_name` varchar(100) NOT NULL default '' COMMENT "Free-form, not validated",
  `bank_aba` varchar(9) NOT NULL default '' COMMENT "Should be nine DIGITS",
  `bank_account` varchar(17) NOT NULL default '' COMMENT "Should be a string of numbers without formatting",
  `bank_account_type` enum('checking','savings') NOT NULL default 'checking' COMMENT "Obvious",
  `date_fund_estimated` date default NULL COMMENT "A calculated estimate of when the loan will be funded",
  `date_fund_actual` date default NULL COMMENT "?: When the loan was actually funded. First vs. most recent when involving failed fund events",
  `date_first_payment` date default NULL COMMENT "?: Date when user is supposed to make first payment OR Date when user made first payment",
  `fund_requested` decimal(7,2) default NULL COMMENT "How much the person is requesting",
  `fund_qualified` decimal(7,2) NOT NULL default '0.00' COMMENT "How much we're willing to give them",
  `fund_actual` decimal(7,2) default NULL COMMENT "How much we ACTUALLY gave them",
  `finance_charge` decimal(7,2) default NULL COMMENT "?: How much the person will pay *each* finance charge OR How much the person will pay *total*",
  `payment_total` decimal(7,2) default NULL COMMENT "?: Total of fund_actual and finance_charge",
  `apr` decimal(9,4) default NULL COMMENT "Annual Percentage Rate",
  `income_monthly` decimal(7,2) NOT NULL default '0.00' COMMENT "Applicant's stated monthly income",
  `income_source` enum('employment','benefits') NOT NULL default 'employment' COMMENT "Self explanatory",
  `income_direct_deposit` enum('no','yes') NOT NULL default 'no' COMMENT "If they receive a paper check or not",
  `income_frequency` enum('weekly','twice_monthly','bi_weekly','monthly') NOT NULL default 'weekly' COMMENT "Must fit into one of these categories",
  `income_date_soap_1` date default NULL COMMENT "?:",
  `income_date_soap_2` date default NULL COMMENT "?:",
  `paydate_model` enum('dw','dwpd','dmdm','wwdw','dm','dwdm','wdw') NOT NULL default 'dw' COMMENT "See `reports_paydate_models`",
  `day_of_week` enum('sun','mon','tue','wed','thu','fri','sat') default NULL COMMENT "Which day of the week the applicant gets paid",
  `last_paydate` date default NULL COMMENT "What their most recent report pay date was, so that we can calculate from there",
  `day_of_month_1` tinyint(3) unsigned default NULL COMMENT "If they are paid on specific days of the month, put them here",
  `day_of_month_2` tinyint(3) unsigned default NULL COMMENT "If they are paid on specific days of the month, put them here",
  `week_1` tinyint(3) unsigned default NULL COMMENT "If they are paid on specific weeks of the month, put them here",
  `week_2` tinyint(3) unsigned default NULL COMMENT "If they are paid on specific weeks of the month, put them here",
  `track_id` varchar(40) default NULL COMMENT "Foreign key",
  `agent_id` int(10) unsigned default NULL COMMENT "Foreign key",
  `agent_id_callcenter` int(10) unsigned default NULL COMMENT "Foreign key",
  `dob` date NOT NULL default '0000-00-00' COMMENT "Date Of Birth",
  `ssn` varchar(9) NOT NULL default '' COMMENT "Social Security Number (no formatting)",
  `legal_id_number` varchar(30) default NULL COMMENT "Official governmental identification number",
  `legal_id_state` char(2) default NULL COMMENT "Official governmental identification home state",
  `legal_id_type` enum('dl','sid','pp') default NULL COMMENT "Official governmental identification type (drivers license, state issued id, passport)",
  `identity_verified` enum('unverified','verified') NOT NULL default 'unverified' COMMENT "If we've contacted them and they seem to be who they say they are",
  `email` varchar(100) NOT NULL default '' COMMENT "The email address they would like us contacting them at",
  `email_verified` enum('unverified','verified') NOT NULL default 'unverified' COMMENT "If we've successfully sent/received mail at their email address",
  `name_last` varchar(50) NOT NULL default '' COMMENT "Their real name",
  `name_first` varchar(50) NOT NULL default '' COMMENT "Their real name",
  `name_middle` varchar(50) default NULL COMMENT "Their real name",
  `name_suffix` varchar(20) default NULL COMMENT "Their real name",
  `street` varchar(100) NOT NULL default '' COMMENT "Street address including building number",
  `unit` varchar(10) default NULL COMMENT "Apartment number, if applicable",
  `city` varchar(30) NOT NULL default '' COMMENT "City name",
  `state` char(2) NOT NULL default '' COMMENT "State",
  `zip_code` varchar(9) NOT NULL default '' COMMENT "Postal location code",
  `tenancy_type` enum('unspecified','own','rent') NOT NULL default 'unspecified' COMMENT "Home ownership",
  `phone_home` varchar(10) NOT NULL default '' COMMENT "No formatting",
  `phone_cell` varchar(10) default NULL COMMENT "No formatting",
  `phone_fax` varchar(10) default NULL COMMENT "No formatting",
  `call_time_pref` enum('no preference','morning','afternoon','evening') NOT NULL default 'no preference' COMMENT "Self explanatory",
  `contact_method_pref` enum('no preference','home phone','work phone','cell phone','email','usps') NOT NULL default 'no preference' COMMENT "Self explanatory",
  `marketing_contact_pref` enum('no preference','phone','email','usps','no contact') NOT NULL default 'no preference' COMMENT "Self explanatory",
  `employer_name` varchar(100) default NULL COMMENT "Who they say their employer is",
  `job_title` varchar(100) default NULL COMMENT "What they say their position is",
  `supervisor` varchar(50) default NULL COMMENT "Who they say is in charge of them",
  `shift` enum('day','swing','grave','other') default NULL COMMENT "What shift they claim to work",
  `date_hire` datetime default NULL COMMENT "What date they claim to have begun work",
  `job_tenure` decimal(4,2) default NULL COMMENT "If the job has a tenure, what amount that is",
  `phone_work` varchar(10) default NULL COMMENT "No formatting",
  `phone_work_ext` varchar(8) default NULL COMMENT "No formatting",
  `work_address_1` varchar(50) default NULL COMMENT "Street address including building number",
  `work_address_2` varchar(50) default NULL COMMENT "Optional suite number and/or ATTN",
  `work_city` varchar(30) default NULL COMMENT "City name",
  `work_state` char(2) default NULL COMMENT "State",
  `work_zip_code` varchar(9) default NULL COMMENT "Postal location code",
  `employment_verified` enum('unverified','verified') NOT NULL default 'unverified' COMMENT "If we've been able to contact their employer and confirm they're working there currently",
  `pwadvid` varchar(40) character set latin1 collate latin1_bin default NULL COMMENT "?:",
  `olp_process` varchar(255) NOT NULL default 'email_confirmation' COMMENT "?:",
  `is_watched` enum('no','yes') NOT NULL COMMENT "If an agent is watching this application closely",
  PRIMARY KEY  (`application_id`),
  UNIQUE KEY `idx_app_archive_db2` (`archive_db2_id`,`company_id`),
  UNIQUE KEY `idx_app_archive_mysql` (`archive_mysql_id`,`company_id`),
  UNIQUE KEY `idx_app_archive_cashline` (`archive_cashline_id`,`company_id`),
  KEY `idx_app_ssn_co_app` (`ssn`,`company_id`,`application_id`),
  KEY `idx_app_lname_co_app` (`name_last`,`company_id`,`application_id`),
  KEY `idx_app_fname_co_app` (`name_first`,`company_id`,`application_id`),
  KEY `idx_app_lname_fname_co_app` (`name_last`,`name_first`,`company_id`,`application_id`),
  KEY `idx_app_login_app` (`login_id`,`company_id`,`application_id`),
  KEY `idx_app_status_co_stsdate` (`application_status_id`,`company_id`,`date_application_status_set`,`application_id`),
  KEY `idx_app_status_co_nxtdate` (`application_status_id`,`company_id`,`date_next_contact`,`application_id`),
  KEY `idx_app_bank_acct_aba_ssn` (`bank_account`,`bank_aba`,`ssn`,`date_created`),
  KEY `idx_app_co_date_status_set` (`company_id`,`date_application_status_set`,`application_id`),
  KEY `idx_app_email_co_date` (`email`,`company_id`,`date_created`),
  KEY `idx_app_ruleset_date` (`rule_set_id`,`date_created`),
  KEY `idx_date_created` (`date_created`),
  KEY `idx_phone_cell` (`phone_cell`(6)),
  KEY `idx_track_id` (`track_id`(6)),
  KEY `idx_olp_process` (`olp_process`(5)),
  KEY `idx_phone_home` (`phone_home`(6)),
  KEY `idx_legal_id_number` (`legal_id_number`(6))
) ENGINE=InnoDB COMMENT="Mostly information unique to the application";
