UPDATE transaction_type SET name = 'Interest Payment' WHERE transaction_type_id = 3;
UPDATE transaction_type SET name = 'Interest' WHERE transaction_type_id = 4;
UPDATE transaction_type SET name = 'Interest Balance Forward' WHERE transaction_type_id = 9;
UPDATE transaction_type SET name = 'Converted Interest Transaction' WHERE transaction_type_id = 32;
UPDATE transaction_type SET name = 'Interest Payment' WHERE transaction_type_id = 50;
UPDATE transaction_type SET name = 'Interest' WHERE transaction_type_id = 51;
UPDATE transaction_type SET name = 'Interest Balance Forward' WHERE transaction_type_id = 56;
UPDATE transaction_type SET name = 'Converted Interest Transaction' WHERE transaction_type_id = 79;
UPDATE transaction_type SET name = 'Interest Payment' WHERE transaction_type_id = 97;
UPDATE transaction_type SET name = 'Interest' WHERE transaction_type_id = 98;
UPDATE transaction_type SET name = 'Interest Balance Forward' WHERE transaction_type_id = 103;
UPDATE transaction_type SET name = 'Converted Interest Transaction' WHERE transaction_type_id = 126;
UPDATE transaction_type SET name = 'Interest Payment' WHERE transaction_type_id = 144;
UPDATE transaction_type SET name = 'Interest' WHERE transaction_type_id = 145;
UPDATE transaction_type SET name = 'Interest Balance Forward' WHERE transaction_type_id = 150;
UPDATE transaction_type SET name = 'Converted Interest Transaction' WHERE transaction_type_id = 173;
UPDATE transaction_type SET name = 'Interest Payment' WHERE transaction_type_id = 191;
UPDATE transaction_type SET name = 'Interest' WHERE transaction_type_id = 192;
UPDATE transaction_type SET name = 'Interest Balance Forward' WHERE transaction_type_id = 197;
UPDATE transaction_type SET name = 'Converted Interest Transaction' WHERE transaction_type_id = 220;

UPDATE event_type SET name = 'Interest Payment' WHERE event_type_id = 3;
UPDATE event_type SET name = 'Interest' WHERE event_type_id = 4;
UPDATE event_type SET name = 'Interest Balance Forward' WHERE event_type_id = 9;
UPDATE event_type SET name = 'Converted Interest Event' WHERE event_type_id = 22; 
UPDATE event_type SET name = 'Interest Payment' WHERE event_type_id = 34; 
UPDATE event_type SET name = 'Interest' WHERE event_type_id = 35; 
UPDATE event_type SET name = 'Interest Balance Forward' WHERE event_type_id = 40; 
UPDATE event_type SET name = 'Converted Interest Event' WHERE event_type_id = 53; 
UPDATE event_type SET name = 'Interest Payment' WHERE event_type_id = 65; 
UPDATE event_type SET name = 'Interest' WHERE event_type_id = 66; 
UPDATE event_type SET name = 'Interest Balance Forward' WHERE event_type_id = 71; 
UPDATE event_type SET name = 'Converted Interest Event' WHERE event_type_id = 84; 
UPDATE event_type SET name = 'Interest Payment' WHERE event_type_id = 96; 
UPDATE event_type SET name = 'Interest' WHERE event_type_id = 97; 
UPDATE event_type SET name = 'Interest Balance Forward' WHERE event_type_id = 102;
UPDATE event_type SET name = 'Converted Interest Event' WHERE event_type_id = 115;
UPDATE event_type SET name = 'Interest Payment' WHERE event_type_id = 127;
UPDATE event_type SET name = 'Interest' WHERE event_type_id = 128;
UPDATE event_type SET name = 'Interest Balance Forward' WHERE event_type_id = 133;
UPDATE event_type SET name = 'Converted Interest Event' WHERE event_type_id = 146;

UPDATE `rule_component_parm` SET description = 'The maximum number of times a interest charge ACH can return before the account goes to internal collections.' WHERE rule_component_parm_id = 11;
UPDATE `rule_component_parm` SET description = 'The maximum number of times a interest charge will be applied to an account.' WHERE rule_component_parm_id = 12;
UPDATE `rule_component_parm` SET description = 'The amount to be applied towards the loan principal after the maximum interest charge only payments rule has been exceeded. This amount is only valid as long as it is less then the loan principal.' WHERE rule_component_parm_id = 13;
UPDATE `rule_component_parm` SET description = 'This will determine the interest charge amount. It will be a percentage of the loan principal.' WHERE rule_component_parm_id = 14;
