## Update correct sending method for docs

UPDATE document_list SET send_method = 'email' WHERE name IN (
'UPS Package Arrived',
'Waiting on UPS',
'Already Active Customer Letter',
'Approval-Fund Letter ACH DE',
'Approval-Fund Letter ACH Jiffy',
'Approval-Fund Letter Check DE',
'Approval-Fund Letter MoneyGram CA',
'Approval-Fund Letter MoneyGram DE',
'Promise to Pay',
'Payment Missed',
'Collection Balance',
'Payment Reminder',
'Payment Reminder CA',
'Credit Card Payment',
'Denial from Veritrac',
'Denial from CL Verify',
'Denial from Credit Bureau',
'Denial from Teletrac',
'Deny',
'Funder Review',
'ID and Social Security Letter',
'Reactivation Letter',
'Online Request Confirmation',
'PayDate Change',
'Phone Request Confirmation',
'Please Call Us',
'Receipt Email Payday',
'Receipt Email CA',
'Requests Benefits',
'Return Letter 1',
'Return Letter 2',
'Return Letter 3',
'Return Letter 4',
'Voided Check Request',
'Withdrawn Letter',
'Zero Balance Letter'
);